<section id="about">
    <h2>JF</h2>
    <img src="<?= $wwwUrl ?>/images/juline.jpg" alt="Juline's profile picture" class="small-img responsive">
    <article>
        <h2>Who is Juline Francisco?</h2>
        <p>Born in Brazil, italian from blood and irish from heart.</p>
        <p>I believe everyone is given the same opportunities, we all have each and every day a chance to start over, to rebuild ourselves. All we need to do is use the time we have wisely.</p>
        <p>Traveling is one of my hobbies, going places I've never been before, success starts where our comfort zone ends. You can always learn from different people and culture, this is what gives life a meaning... to contribute. </p>
    </article>
    <article>
        <h2>Career</h2>
        <p>I hold a degree in Physical Education</p>
        <p>This feeling of looking after people has been part of me since a very young age, I've always looked up to my mother who would always help others. After months brainstorming how I could make the world a better place, I felt in love with physical education, for me the human body is fantastic, the way we move our bodies on a daily-basis has a very big impact.</p>
        <p>I always say <q>It's not about how you look</q> but how you feel. Since then, I've never stopped. I've attended fairs, workshops, lectures and so on. </p>
        <p>I now keep my purpose of helping people to be healthier and feel comfortable in their own bodies.</p>
    </article>
</section>

